name: Playwright API Tests

on:
  push:
    branches: [main, master]
    paths:
      - 'api/**'  
      - 'tests/api/**'
  pull_request:
    branches: [main, master]
    paths:
      - 'api/**'
      - 'tests/api/**'
jobs:
  run_api_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Run API tests
        run: npx playwright test tests/api --reporter=html,junit

      - name: Upload Playwright HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: playwright-html-report-api
          path: playwright-report/
